name: mobile_pos_adminpanell
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  rflutter_alert: ^2.0.7
  provider: ^6.1.1
  
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  flutter_datetime_picker_plus: ^2.1.0
  intl: ^0.19.0
  animated_custom_dropdown: ^1.4.0
  cached_network_image: ^3.3.1
  fast_cached_network_image: ^1.1.0
  qr_flutter: ^4.1.0
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
 
  
